# Generated by Django 6.0.2 on 2026-02-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="ratting",
            new_name="rating",
        ),
    ]
