# Generated by Django 6.0.2 on 2026-02-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="image_slug",
            field=models.SlugField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="caption",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(upload_to="gallery/"),
        ),
    ]
