# Generated by Django 6.0.2 on 2026-02-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_gallery_image_slug_alter_gallery_caption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="excerpt",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
