# Generated by Django 5.1 on 2026-02-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_backfill_gallery_slugs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="gallery",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
