# Generated by Django 6.0.2 on 2026-02-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todos",
            old_name="note_slug",
            new_name="todo_slug",
        ),
    ]
