# Generated by Django 6.0.2 on 2026-02-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_rename_note_slug_todos_todo_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todos",
            old_name="desciption",
            new_name="description",
        ),
    ]
