# Generated by Django 6.0.2 on 2026-02-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_rename_desciption_todos_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todos",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
